---
  - name: comment line 1
    become: true
    ansible.builtin.lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^- type: filestream$'
      line: '#- type: filestream'
      
  - name: comment line 2
    become: true
    ansible.builtin.lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^  id: my-filestream-id$'
      line: '# id: my-filestream-id'
      
  - name: comment line 3
    become: true
    ansible.builtin.lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^    - \/var\/log\/\*\.log$'
      line: '# - /var/log/*.log'
      
  - name: comment line 4
    become: true
    ansible.builtin.lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^  enabled: false$'
      line: '# enabled: false'
      
  - name: comment line 5
    become: true
    ansible.builtin.lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^  paths:$'
      line: '# paths:'
      
  - name: replace elasticsearch output
    become: true
    ansible.builtin.lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^  hosts: \["localhost:9200"\]'
      line: '  hosts: ["{{ elasticsearch }}:9200"]'
      
  - name: nginx module enabled
    become: true
    ansible.builtin.command: mv /etc/filebeat/modules.d/nginx.yml.disabled /etc/filebeat/modules.d/nginx.yml
    
  - name: add setup kibana
    become: true
    ansible.builtin.lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^setup\\.kibana'
      insertafter: '^setup.kibana'
      line: '  host: "{{ kibana }}:5601"'
      
  - name: replace filebeat inputs
    become: true
    ansible.builtin.blockinfile:
      path: /etc/filebeat/filebeat.yml
      insertafter: '^filebeat.inputs'
      block: |
        - type: log
          enabled: true
          paths:
            - /var/log/nginx/access.log
          fields:
            type: nginx_access
          fields_under_root: true
          scan_frequency: 5s
        - type: log
          enabled: true
          paths:
            - /var/log/nginx/error.log
          fields:
            type: nginx_error
          fields_under_root: true
          scan_frequency: 5s

